### ISSUE TITLE
TypeError: copy_events() takes 6 positional arguments but 7 were given

### ISSUE THREAD

**Issue by sceniclife** [cognitedata/cognite-replicator#133]
Attempting to copy events will error with the following error:

`TypeError: copy_events() takes 6 positional arguments but 7 were given
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/Users/viet/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 870, in run`

Environment:
`[tool.poetry.dependencies]
python = "^3.8"
cognite-replicator = "^0.8.1"`

**Comment by sceniclife** [comment]
On Pull Request #123: The argument dst_ts was added to the replication.thread parameters. The replication.thread function is used for multiple CDF types… not just TimeSeries. Because dst_ts was added to replication.thread parameters, the Event call to replication.thread is broken

**Comment by sceniclife** [comment]
Possible solution is to add `target_external_ids` to all other replicate functions like the time_series one. This will add the ability to all other data types (event, filemetadata).

Then change dst_ts to dst_list, make it usable for all other data types.

Then consume the list in the data types copy to only filter out the dst_list

**Comment by gaetan-h** [comment]
This should now be fixed with https://github.com/cognitedata/cognite-replicator/pull/134
