### ISSUE TITLE
Broken function parameters to File and Events

### ISSUE THREAD

**Issue by sceniclife** [cognitedata/cognite-replicator#156]
https://github.com/cognitedata/cognite-replicator/blob/c2d70d5738fc6b806e72408fb157d30d64c38e63/cognite/replicator/replication.py#L362

@jorge-sanchez-2020 
@gaetan-h 
@petreeb 

Hey, FYI, the replication.thread function is shared by TimeSeries, File, and Events. If you change the signature parameters here, you NEED to change it in timeseries.py, files.py, and events.py

It was only changed in timeseries.py. Files and Event replication is currently broken.
https://github.com/cognitedata/cognite-replicator/commit/5380a2192d93be193ebd683c9d2569cac677d1ee#

**Comment by gaetan-h** [comment]
@jorge-sanchez-2020 can you look into this? Thanks

**Comment by sceniclife** [comment]
I've already made the fix in the attached PR.

**Comment by gaetan-h** [comment]
Perfect
