### ISSUE TITLE
Dataset Awareness

### ISSUE THREAD

**Issue by bbrandt** [cognitedata/cognite-replicator#173]
We have discovered that when using Cognite Replicator, our source Project has dataset id's set, but in the target Project all dataset id's are null.  Please add support for replicating datasets and setting dataset id's on all entities to the replicator.

The workaround we will be operating on in the meantime is to run a script afterward to copy the Datasets and set the dataset id's.

**Comment by gaetan-h** [comment]
@bbrandt the latest version of the replicator now supports datasets
https://github.com/cognitedata/cognite-replicator/blob/master/config/default.yml#L54
It also introduces a new configuration file format. 
https://github.com/cognitedata/cognite-replicator/blob/master/config/default.yml
