### ISSUE TITLE
Continous deployment pipeline

### ISSUE THREAD

**Issue by eventh** [cognitedata/cognite-replicator#35]
- [x] Publish package to PyPI
- [x] Publish docker image to docker hub
- [x] Publish code coverage
- [x] Publish documentation on readthedocs

**Comment by eventh** [comment]
https://github.com/cognitedata/cognite-grafana-datasource/blob/master/Jenkinsfile examples for pushing the docker image to docker hub.

**Comment by tristan-cognite** [comment]
#78
