### ISSUE TITLE
Unnecessary batching of create time series/events?

### ISSUE THREAD

**Issue by erlendvollset** [cognitedata/cognite-replicator#58]
I see that time series/events are split into batches of 10,000 and posted in parallell. The SDK already does this, so it shouldn't be necessary to do it here as well.

Also, the batch_size passed to `replicate()` is not respected. A dynamic batch size is calculated based on the number of threads allocated.

**Comment by sceniclife** [comment]
@erlendvollset Can you help me out and clarify what you said about the SDK already batching 10,000?
